In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cpu


### Basics

In [48]:
## introduction of Tensors
## features 

## scaler == value
scaler= torch.tensor(7)
scaler


tensor(7)

In [ ]:
## dimension of the tensor
print(scaler.ndim)

## values of tensor
scaler.item()



7

In [ ]:
## vector

vector=torch.tensor([7.,7]) ## should be same data type or it will convert it
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [49]:
matrix=torch.tensor([[4,5],
                     
                     [44,55]])

## 2D tensor here

In [16]:
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [54]:
## Tensors
## 3D tensor extra pair of bracket

TENSOR=torch.tensor([[[4,5],
                     [44,55],
                     [33,44]]]) ## each row should have equal number of elements should be same

In [53]:
TENSOR

tensor([[[ 4,  5],
         [44, 55],
         [33, 44]]])

In [ ]:
print(TENSOR.shape)

print(TENSOR.ndim) ## 1st -> 1 "one block of code" 3 rows and 2 column

torch.Size([1, 3, 2])
3


In [55]:
TENSOR1=torch.tensor([
                    [[4,5],
                     [44,55],
                     [33,44]],
                     ## here another block of code so check this 
                     [[4,5],
                     [44,55],
                     [33,44]]
                     ]
                     )
print(TENSOR1)
print(TENSOR1.shape)
print(TENSOR1.ndim)

tensor([[[ 4,  5],
         [44, 55],
         [33, 44]],

        [[ 4,  5],
         [44, 55],
         [33, 44]]])
torch.Size([2, 3, 2])
3


### Tensor Operations and gradients

In [76]:
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)

In [ ]:
y=w*x+b
y

y.backward() ## necessary for gradient

In [78]:
## derivative 

print('dy/dx', b.grad) 

dy/dx tensor(1.)


In [82]:
import numpy as np

x=np.array([[1,2],[3,4]])
print(x)
x.shape

[[1 2]
 [3 4]]


(2, 2)

In [86]:
xt=torch.from_numpy(x)
print(xt)

print(x.dtype,',',y.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
int32 , torch.float32
